const constants = {
    SET_USER: 'SET_USER',
    SET_TOKEN: 'SET_TOKEN',
    SET_LOADER: 'SET_LOADER',
    SET_LOGIN_ERROR: 'SET_LOGIN_ERROR',
    CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
    SET_LANGUAGE: 'SET_LANGUAGE',
    SET_CART: 'SET_CART',
    CART_ADD: 'CART_ADD',
    CART_CLEAR: 'CART_CLEAR',
    CART_UPDATE_QUANTITY: 'CART_UPDATE_QUANTITY',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
}

export default constants
